apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yuc217/DevOps-Docker-Kubernetes
    path: par4/todo-manifests/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true