apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yuc217/DevOps-Docker-Kubernetes
    path: part4/todo-manifests/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true