apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: shared-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi