apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: todo-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: broadcaster
        image: yuc217/broadcaster:latest
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-secret
              key: webhook-url