apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: google/cloud-sdk:alpine 
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/secrets/gcp-credentials/key.json"
            volumeMounts:
              - name: gcp-credentials
                mountPath: /secrets/gcp-credentials
                readOnly: true
            command:
              - /bin/sh
              - -c
              - |
                # Backup PostgreSQL database using pg_dump
                pg_dump -h postgres -U postgres -d todo > /tmp/backup.sql

                # Upload backup to Google Cloud Storage
                gsutil cp /tmp/backup.sql gs://devops-backups-bucket/$(date +\%F)-backup.sql
          restartPolicy: OnFailure
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials
