apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-apps
resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - todo-frontend-deployment.yaml
  - todo-frontend-service.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - ingress.yaml
images:
- name: PROJECT/IMAGE
  newName: yuc217/ping-pong