apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: ping-pong
 namespace: devops-apps
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: ping-pong
 minReplicas: 1
 maxReplicas: 6
 metrics:
 - type: Resource
   resource:
     name: memory
     target:
       type: Utilization
       averageUtilization: 50