apiVersion: v1
kind: ConfigMap
metadata:
  name: fetch-scripts
data:
  fetch-page.sh: |
    #!/bin/sh
    wget -qO- https://en.wikipedia.org/wiki/Kubernetes > /shared-data/index.html
    
  random-page.sh: |
    #!/bin/sh
    while true; do
      # Generate random sleep duration between 5 and 15 minutes
      sleep_duration=$(( ( RANDOM % 600 ) + 300 ))
      echo "Sleeping for $sleep_duration seconds..."
      sleep $sleep_duration
      
      # Fetch random Wikipedia page
      echo "Fetching random Wikipedia page..."
      wget -qO- https://en.wikipedia.org/wiki/Special:Random > /shared-data/random-page.html
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikipedia-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikipedia-server
  template:
    metadata:
      labels:
        app: wikipedia-server
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: scripts
        configMap:
          name: fetch-scripts
          defaultMode: 0755 
      
      # Init container
      initContainers:
      - name: init-fetch
        image: curlimages/curl:latest
        command: ["/scripts/fetch-page.sh"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        - name: scripts
          mountPath: /scripts
      
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      
      # Sidecar container 
      - name: random-page-fetcher
        image: curlimages/curl:latest
        command: ["/scripts/random-page.sh"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        - name: scripts
          mountPath: /scripts

---
apiVersion: v1
kind: Service
metadata:
  name: wikipedia-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wikipedia-server