apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller
rules:
  - apiGroups: ["example.com"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller
subjects:
  - kind: ServiceAccount
    name: dummysite-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: dummysite-controller
  apiGroup: rbac.authorization.k8s.io