apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-cronjob
  namespace: todo-app
spec:
  schedule: "0 * * * *" 
  # schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cronjob
            image: todo-cronjob:latest
            command: ["/bin/sh", "/usr/local/bin/random-todo.sh"]
          restartPolicy: OnFailure