# for exercise 5.02
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"todo-backend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-backend"}},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"todo-backend"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_USER","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USER","name":"postgres-secret"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"postgres-secret"}}},{"name":"POSTGRES_DB","value":"todo"},{"name":"POSTGRES_HOST","value":"postgres.todo-app.svc.cluster.local"},{"name":"POSTGRES_PORT","value":"5432"}],"image":"yuc217/todo-backend:latest","imagePullPolicy":"Always","name":"todo-backend","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":10,"periodSeconds":5}}]}}}}
    creationTimestamp: "2025-01-30T19:13:19Z"
    generation: 1
    name: todo-backend
    namespace: default
    resourceVersion: "27653"
    uid: ad122751-85f4-4261-8374-b23e8b2b5d10
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        creationTimestamp: null
        labels:
          app: todo-backend
      spec:
        containers:
        - env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secret
          - name: POSTGRES_DB
            value: todo
          - name: POSTGRES_HOST
            value: postgres.todo-app.svc.cluster.local
          - name: POSTGRES_PORT
            value: "5432"
          image: yuc217/todo-backend:latest
          imagePullPolicy: Always
          name: todo-backend
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2025-01-30T19:13:19Z"
      lastUpdateTime: "2025-01-30T19:13:19Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-01-30T19:13:19Z"
      lastUpdateTime: "2025-01-30T19:13:20Z"
      message: ReplicaSet "todo-backend-54479c7c9c" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""