- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"todo-frontend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"todo-frontend"}},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"todo-frontend"}},"spec":{"containers":[{"image":"yuc217/todo-frontend:latest","imagePullPolicy":"Always","name":"todo-frontend","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":10,"periodSeconds":5}}]}}}}
    creationTimestamp: "2025-01-30T19:17:30Z"
    generation: 1
    name: todo-frontend
    namespace: default
    resourceVersion: "30249"
    uid: de75e9f0-e65f-413b-9e8e-f300aa53a775
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-frontend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        creationTimestamp: null
        labels:
          app: todo-frontend
      spec:
        containers:
        - image: yuc217/todo-frontend:latest
          imagePullPolicy: Always
          name: todo-frontend
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2025-01-30T19:17:30Z"
      lastUpdateTime: "2025-01-30T19:17:30Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-01-30T19:17:30Z"
      lastUpdateTime: "2025-01-30T19:17:30Z"
      message: ReplicaSet "todo-frontend-d44d478fb" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""