name: build and publish for GitOps

on:
    workflow_dispatch:

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t yuc217/ping-pong:$GITHUB_SHA ./part3/ping-pong/
          docker push yuc217/ping-pong:$GITHUB_SHA
    
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
  
      - name: Use right image
        run: |-
            cd part4/manifests/
            kustomize edit set image PROJECT/IMAGE=yuc217/ping-pong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
            add: 'kustomization.yaml'
            message: New version released ${{ github.sha }}