name: Delete on Branch Deletion

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-environment:
    name: Delete Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Set Namespace
        id: set-namespace
        run: |
          echo "NAMESPACE=${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Verify Namespace
        run: |
          kubectl get namespace ${{ env.NAMESPACE }}

      - name: Delete Namespace
        run: |
          kubectl delete namespace ${{ env.NAMESPACE }}
